Logout component v1
AlexGoIT/project-V3w84M pull request #30
Opened 2023-11-12 18:45 UTC by strictly-rigid

2023-11-12 20:42 UTC, AlexGoIT commented on src/pages/Profile/UserCard/images/Ellipse 3.png
В назвах файлів не повинно бути великих літер і пробілів!

2023-11-12 20:44 UTC, AlexGoIT requested changes
Необхідно виправити назви файлів зображень.

2023-11-12 20:44 UTC, AlexGoIT commented on src/pages/Profile/UserCard/images/Vector.png
В назвах файлів не повинно бути великих літер і пробілів!

2023-11-12 20:44 UTC, AlexGoIT commented on src/pages/Profile/UserCard/images/check mark.png
В назвах файлів не повинно бути великих літер і пробілів!

2023-11-13 08:05 UTC, Olenakas approved these changes

2023-11-13 08:07 UTC, Olenakas approved these changes

2023-11-13 08:09 UTC, AlexGoIT approved these changes

2023-11-13 08:10 UTC, merged